var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var Email = mongoose.SchemaTypes.Email;

var TwitSchema = new Schema({
  created_at: {type:Date, default: Date.now},
  id: {type:Number, default: 0},
  id_str: {type:String, default: '0'},
  text: {type:String, default: ''},
  source: String,
  truncated: Boolean,
  in_reply_to_status_id: Number,
  in_reply_to_status_id_str: String,
  in_reply_to_user_id: Number,
  in_reply_to_user_id_str: String,
  in_reply_to_screen_name: String,
  user: {
    created_at: String,
    notifications: String,
    follow_request_sent: String,
    following: String,
    default_profile_image: String,
    default_profile: String,
    profile_use_background_image: String,
    profile_text_color: String,
    profile_sidebar_fill_color: String,
    profile_sidebar_border_color: String,
    profile_link_color: String,
    profile_banner_url: String,
    profile_image_url_https: String,
    profile_image_url: String,
    profile_background_tile: String,
    profile_background_image_url_https: String,
    profile_background_image_url: String,
    profile_background_color: String,
    is_translation_enabled: Boolean,
    is_translator: Boolean,
    contributors_enabled: Boolean,
    lang: String,
    statuses_count: Number,
    verified: Boolean,
    geo_enabled: Boolean,
    time_zone: String,
    utc_offset: String,
    favourites_count: Number,
    listed_count: Number,
    friends_count: Number,
    followers_count: Number,
    'protected': Boolean,
    description: String,
    url: String,
    location: String,
    screen_name: String,
    name: String,
    id_str: String,
    id: Number,
  },
  geo: String,
  coordinates: String,
  place: String,
  contributors: String,
  retweeted_status: Schema.Types.Mixed,
  retweet_count: Number,
  favorite_count: Number,
  entities: 
   { 
   	 hashtags: [Schema.Types.Mixed],
     symbols:  [Schema.Types.Mixed],
     urls:     [Schema.Types.Mixed],
     user_mentions: [Schema.Types.Mixed],
    },
  favorited: Boolean,
  retweeted: Boolean,
  possibly_sensitive: Boolean,
  lang: String }
  );

module.exports = mongoose.model('TwitSchema', TwitSchema);